failFast: true

comments:
  UndocumentedPublicClass:
    active: false
  UndocumentedPublicFunction:
    active: false

potential-bugs:
  UnsafeCast:
    active: false

style:
  ExpressionBodySyntax:
    active: false
  ForbiddenComment:
    active: true
    values: 'FIXME:,STOPSHIP:'

naming:
   MatchingDeclarationName:
    active: false
   FunctionMaxLength:
    active: false